name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t my-dockerhub-username/my-app:latest .

    - name: Push Docker Image
      run: docker push my-dockerhub-username/my-app:latest
